eftafmo/dataviz

assets/css/normalize.css, assets/js/components/Mechanisms.vue
=> styling for financial mechanism legend

.babelrc, package.json, webpack.config.js
old vs new:
- initial builds: 16564ms -> 7724ms
- hot re-build: 1279ms -> 1144ms
=> use buble instead of babel

assets/js/components/Beneficiaries.vue, assets/js/components/Mechanisms.vue, assets/js/components/global/filters.js, assets/js/components/globalfilter.vue, assets/js/components/includes/DropdownFilter.vue, assets/js/components/includes/FMLegend.vue, assets/js/components/index.js, assets/js/components/mixins/Base.vue, assets/js/components/mixins/WithFMs.vue, templates/grants.html
Dropdown and global filter components
=> Dropdown filter

dv/localsettings.py.example, dv/management/commands/import.py, dv/management/commands/import_news.py, dv/settings.py, dv/urls/api.py
=> Use Django file caching for .json urls. Fixes #341

dv/search_indexes.py, dv/views/frontend.py
=> Default sorting. Fixes #391

dv/search_indexes.py, dv/urls/frontend.py, dv/views/frontend.py, templates/search.html, templates/search/indexes/dv/news_text.txt
=> News search. Fixes #392

dv/search_indexes.py
=> Update state names from programme outcomes. Fixes #429

dv/search_indexes.py
@melish please review 😄 
Fixes #447.
=> Fix financial mechanism on news index

assets/js/components/ProjectsMap.vue
=> related to #433, highlight nuts3 region on click

dv/views/facets_rules.py
=> Move organisation role before state name

dv/views/frontend.py, templates/search/filters/city.html, templates/search/filters/geotarget.html, templates/search/filters/project_name.html
=> Show facet counts on ajax select2

templates/search/filters/city.html, templates/search/filters/country.html, templates/search/filters/financial_mechanism_ss.html, templates/search/filters/geotarget.html, templates/search/filters/inputs/ajax_select2.html, templates/search/filters/inputs/checkboxes.html, templates/search/filters/inputs/select2.html, templates/search/filters/org_type.html, templates/search/filters/org_type_category.html, templates/search/filters/outcome_ss.html, templates/search/filters/priority_sector_ss.html, templates/search/filters/programme_area_ss.html, templates/search/filters/programme_name.html, templates/search/filters/programme_status.html, templates/search/filters/project_name.html, templates/search/filters/project_status.html, templates/search/filters/role_ss.html, templates/search/filters/state_name.html, templates/search/filters/theme_ss.html
=> Refactor templates for search facets

dv/search_indexes.py
=> Project code in organisation project name

dv/search_indexes.py, dv/urls/api.py, dv/views/frontend.py, templates/search/filters/outcome_ss.html
=> Ajax select for outcome_ss

dv/templatetags/tags.py, templates/search/filters/inputs/ajax_select2.html, templates/search/filters/inputs/checkboxes.html, templates/search/filters/inputs/select2.html, templates/search/main.html
=> Don't load not selected ajax facets

dv/views/frontend.py
=> Move FacetedSearchView constants queries at first init, instead of load

dv/search_indexes.py, dv/views/frontend.py, templates/search/indexes/dv/organisation_text.txt, templates/search/indexes/dv/programme_text.txt
=> Refactor indexing queries

dv/views/frontend.py
=> Fix sudden scroll error bug

dv/views/frontend.py, templates/search/main.html
=> [refs #540] Fix export multiple field values

dv/settings.py, package.json, requirements.txt
- Updated axios in package.json
- Updated django-material, Jinja2 and djangorestframework in requirements.txt
=> Fix security alerts.

README.md, requirements.txt
Fix readme and requirements file
=> Fix instructions for dev install

INSTALLATION.md, docker-compose-azure.yml, docker/set_context.sh, docker/set_context_production.sh, docker/set_context_staging.sh
Configuration changes that came about when attempting to actually deploy to the production Azure account.
=> Prepare Azure deployment to production

assets/dataviz.js, dv/context.py, package-lock.json, package.json
- upgraded sentry library for vue to @sentry/vue
- fixed adding sentry in DEBUG mode, included environment in data sent to sentry
=> Sentry upgrade and fix adding sentry in DEBUG mode

assets/js/components/GlobalGoalsMechanism.vue, assets/js/components/GoalsSidebar.vue, assets/js/components/PartnersMechanisms.vue, dv/views/api.py
https://helpdesk.eaudeweb.ro/issues/11270
=> Final changes to the Global Goals page (#11270)

dv/management/commands/import.py
Refs https://helpdesk.eaudeweb.ro/issues/17315
=> Use HostPA/HostPS columns if there are multiple values in the import
